all: compile@echo -e '[INFO] Done!’
clean:@echo -e '[INFO] Cleaning Up..'@-rm -rf workspace/CS344PA1/src/*.class
compile:@echo -e '[INFO] Compiling the Source..'@javac -d . workspace/CS344PA1/src/CS455/overlay/node/*.java

